ruta: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/israelcarreramanzaneque_proyectoscompartidos?useSSL=false
user_bd: root
password_bd: quevedo2dam
driver: com.mysql.cj.jdbc.Driver
passKeyStore: root
nombreKeyStore: servidor
